# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-21 00:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('language', models.CharField(max_length=3)),
                ('credit', models.IntegerField()),
            ],
            options={
                'db_table': 'Course',
            },
        ),
        migrations.CreateModel(
            name='Coursecomponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('p1', models.IntegerField(blank=True, null=True)),
                ('p2', models.IntegerField(blank=True, null=True)),
                ('p3', models.IntegerField(blank=True, null=True)),
                ('p4', models.IntegerField(blank=True, null=True)),
                ('p5', models.IntegerField(blank=True, null=True)),
                ('course_code', models.ForeignKey(db_column='Course_code', on_delete=django.db.models.deletion.DO_NOTHING, to='coreapp.Course')),
            ],
            options={
                'db_table': 'CourseComponent',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('class_code', models.CharField(max_length=7)),
                ('degree_program', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.ForeignKey(db_column='Course_code', on_delete=django.db.models.deletion.DO_NOTHING, to='coreapp.Course')),
                ('groups_code', models.ForeignKey(db_column='Groups_code', on_delete=django.db.models.deletion.DO_NOTHING, to='coreapp.Groups')),
            ],
            options={
                'db_table': 'Participation',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('username', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('forename', models.CharField(max_length=45)),
                ('surname', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Teacher',
            },
        ),
        migrations.AddField(
            model_name='coursecomponent',
            name='teacher_username',
            field=models.ForeignKey(db_column='Teacher_username', on_delete=django.db.models.deletion.DO_NOTHING, to='coreapp.Teacher'),
        ),
    ]
